config/routes.rb
Rails.application.routes.draw do
  resource :wechat, only: [:show, :create]
  resources :visitors
  get 'auth/wechat/callback', to: 'wechat/welcome#create'

  mount ChinaCity::Engine => '/china_city'

  namespace :admin do
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    resources :users
    resources :faqs do
      member do
        post :move_to_top
        post :move_to_bottom
        post :move_higher
        post :move_lower
      end
    end
    resources :wechat_users
    resources :view_logs
    resources :addresses
    resources :shared_logs, only: [:index, :create]
    resources :wechat_tags
    resources :users, only: [:index, :show, :update] do
      resources :shared_logs, only:[:index]
      resources :wiew_logs, only: [:index]
    end

    resources :wechat_tags do
      member do
        get :users
      end
    end

    root 'sessions#new'
  end

  namespace :wechat do
    get 'home', to: 'home#index'
    get 'user' => 'user#index'

    resources :addresses

    resources :shared_logs, only: [:create] do
      resource :user
    end
  end


  root  'visitors#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/addresses_controller.rb
class Admin::AddressesController < Admin::BaseController

  def index
    @addresses = current_user.addresses.order('is_default desc, created_at desc')

  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.user_id = current_user.id
    if @address.save
      after_success_save()
    else
      flash[:alert] = @address.errors.full_messages.join(',')
      render :new

    end
  end

  def edit

  end

  def update
    if @address.update_attributes(address_params)
      after_success_save()
    else
      flash[:alert] = @address.errors.full_messages.join(',')
      render :edit
    end

  end

  def destroy
    @address.destroy
  end

  private
  def address_params
    params.require(:address).permit(:name, :phone, :province_code, :city_code, :street, :is_default)
  end

  def after_success_save

  end
end

app/controllers/wechat/addresses_controller.rb
class Wechat::AddressesController < Wechat::BaseController

  def index
    @addresses = current_user.addresses.order('is_default desc, created_at desc')
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.user_id = current_user.id
    if @address.save
      after_success_save()
    else
      flash[:alert] = @address.errors.full_messages.join(',')
      render :new
    end
  end

  def edit

  end

  def update
    if @address.update_attributes(address_params)
      after_success_save()
    else
      flash[:alert] = @address.errors.full_messages.join(',')
      render :edit
    end

  end

  def destroy
    @address.destroy
  end

  private
  def address_params
    params.require(:address).permit(:name, :phone, :province_code, :city_code, :street, :is_default)
  end

  def after_success_save

  end

end

app/helpers/admin/addresses_helper.rb
module Admin::AddressesHelper
end

app/helpers/wechat/addresses_helper.rb
module Wechat::AddressesHelper
end

app/views/admin/addresses/_form.html.slim
.page.pb60
  = form_for [:admin, @address], html: { class: 'default-form', id: 'address_edit_form' } do |f|
    /.form-group
    /  .form-input
    /    = f.text_field :name, class: 'form-control', placeholder: '请输入收货人姓名'
    /.form-group
    /  .form-input
    /    = f.telephone_field :phone, class: 'form-control', placeholder: '请输入收货人手机号码'
    .mt10
      .city-group
        .form-group.form-select
          select.form-control.city-select name='address[province_code]'
            option value='-1' 请选择省份
            = options_for_select(ChinaCity.list, @address.province_code)
        .form-group.form-select
          select.form-control.city-select name='address[city_code]'
            option value='-1' 请选择城市
            - if @address.province_code.present?
              = options_for_select(ChinaCity.list(@address.province_code), @address.city_code)
        .form-group.form-select
          select.form-control.city-select name='address[district_code]'
            option value='-1' 请选择地区
            - if @address.city_code.present?
              = options_for_select(ChinaCity.list(@address.city_code), @address.district_code)

      .form-group
        .form-input
          = f.text_area :street, class: 'form-control', placeholder: '请输入详细地址'
    .mt10
      label.set-address-default#set_default_address
        .pull-left 设为默认地址
        = f.check_box :is_default, class: 'checkbox pull-right'

    - if @address.persisted?
      .clearfix
        .remove-address#remove_address data-url=url_for([:admin, @order, @address]) 删除该地址

    .btn-group.foot
      .item
        = submit_tag '保存地址', class: 'button btn-block btn-radius btn-cyan', id: 'address_edit_submit'

app/views/admin/addresses/index.html.slim
.page.pb60
  .top-bar
    .breadcrumb
      = link_to wechat_home_path, class: 'item' do
        span.icon.icon-home
      = link_to wechat_user_path, class: 'item' do
        | 个人中心
      .item 收货地址

    = link_to new_admin_address_path, class: 'button btn-radius btn-orange-line' do
      span.icon.icon-add
      | 新建地址

  .address-list
    - @addresses.each do |address|
      = link_to edit_admin_address_path(address), class: 'item right-arr-item default' do
        p
          strong 收件人：
          /= address.name
        p
          strong 手机号码：
          /= address.phone
        p
          strong 收货地址：
          = address.display
        - if address.is_default
          .default-icon
            .icon.icon-location
            p 默认地址

app/views/admin/addresses/new.html.slim
= render partial: 'form'