config/routes.rb
Rails.application.routes.draw do
  resource :wechat, only: [:show, :create]
  resources :visitors
  get 'auth/wechat/callback', to: 'wechat/welcome#create'

  mount ChinaCity::Engine => '/china_city'

  namespace :admin do
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    resources :users
    resources :faqs do
      member do
        post :move_to_top
        post :move_to_bottom
        post :move_higher
        post :move_lower
      end
    end
    resources :wechat_users
    resources :view_logs
    resources :addresses
    resources :shared_logs, only: [:index, :create]
    resources :wechat_tags
    resources :users, only: [:index, :show, :update] do
      resources :shared_logs, only:[:index]
      resources :wiew_logs, only: [:index]
    end

    resources :wechat_tags do
      member do
        get :users
      end
    end

    root 'sessions#new'
  end

  namespace :wechat do
    get 'home', to: 'home#index'
    get 'user' => 'user#index'

    resources :addresses

    resources :shared_logs, only: [:create] do
      resource :user
    end
  end


  root  'visitors#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/view_log.rb
class ViewLog < ApplicationRecord

  belongs_to :viewer, class_name: 'User'
  belongs_to :shared_user, class_name: 'User'

end

app/controllers/admin/view_logs_controller.rb
class Admin::ViewLogsController < Admin::BaseController

  def index
    if params[:user_id]
      @user = User.find_by_id(params[:user_id])
      @view_logs = ViewLog.select('view_logs.*, viewers.nickname as viewer_nickname').joins('join users as viewers on viewers.id = view_logs.viewer_id').where(shared_user_id: @user.id)
    else
      @view_logs = ViewLog.select('view_logs.*, shared_users.nickname as shared_user_nickname, viewers.nickname as viewer_nickname').joins('join users as shared_users on shared_users.id = view_logs.shared_user_id').joins('join users as viewers on viewers.id = view_logs.viewer_id')

      if @shared_user_name = params[:shared_user_name].presence
        @view_logs = @view_logs.where('shared_users.nickname like :name', name: '%' + @shared_user_name+ '%')
      end
    end

    if @viewer_name = params[:viewer_name].presence
      @view_logs = @view_logs.where('viewers.nickname like :name', name: '%' + @viewer_name + '%')
    end

    if @uri = params[:uri].presence
      @view_logs = @view_logs.where('uri like ?', '%'+ @uri + '%')
    end

    @view_logs = @view_logs.order('created_at desc').page(params[:page]).per(20)

  end

end

app/helpers/admin/view_logs_helper.rb
module Admin::ViewLogsHelper
end

app/views/admin/view_logs/_list.html.slim
/small= "Total: #{ViewLog.count}"
small= "Total: #{@view_logs.total_count}"
table.table.table-striped
  thead
    tr
      th ViewLog ID
      - if @user.blank?
        th= ViewLog.human_attribute_name(:shared_user_id)
      th= ViewLog.human_attribute_name(:viewer_id)
      th= ViewLog.human_attribute_name(:uri)
      th 时间
  tbody
    - @view_logs.each do |view_log|
      tr
        td= view_log.id
        - if @user.blank?
          td
            = link_to admin_user_path(view_log.shared_user_id) do
              = view_log.shared_user_nickname.presence || view.shared_user_realname.presence
        td
          = link_to admin_user_path(view_log.viewer_id) do
            = view_log.viewer_name.presence || view_log.viewer_nickname.presence || view.viewer_realname.presence
        td= view_log.uri
        td= view_log.created_at.localtime.strftime("%Y年%m月%d日 %H:%M")

.pageList.text-center
  = paginate @view_logs

app/views/admin/view_logs/index.html.slim
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-8
    h2 分享点击日志
    ol.breadcrumb
      li= link_to '首页', admin_root_path
      li.active 列表

.wrapper.wrapper-content.animated.fadeInRight.white-bg
  .ibox.float-e-margins
    .ibox-content
      =form_tag params.permit(:user_id), method: :get, class: 'form-inline order-filter-form m-b' do
        - if @user.blank?
          .form-group.m-r
            = label_tag :shared_user_name, ViewLog.human_attribute_name(:shared_user_id)
            | &nbsp;&nbsp;
            = text_field_tag :shared_user_name, @shared_user_name, class: 'form-control'
        .form-group.m-r
          = label_tag :viewer_name, ViewLog.human_attribute_name(:viewer_id)
          | &nbsp;&nbsp;
          = text_field_tag :viewer_name, @viewer_name, class: 'form-control'
        .form-group.m-r
          = label_tag :uri, ViewLog.human_attribute_name(:uri)
          | &nbsp;&nbsp;
          = text_field_tag :uri, @uri, class: 'form-control'

        = submit_tag '搜索', class: 'btn btn-success'

    = render 'list'