config/routes.rb
Rails.application.routes.draw do
  resource :wechat, only: [:show, :create]
  resources :visitors
  get 'auth/wechat/callback', to: 'wechat/welcome#create'

  mount ChinaCity::Engine => '/china_city'

  namespace :admin do
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    resources :users
    resources :faqs do
      member do
        post :move_to_top
        post :move_to_bottom
        post :move_higher
        post :move_lower
      end
    end
    resources :wechat_users
    resources :view_logs
    resources :addresses
    resources :shared_logs, only: [:index, :create]
    resources :wechat_tags
    resources :users, only: [:index, :show, :update] do
      resources :shared_logs, only:[:index]
      resources :wiew_logs, only: [:index]
    end

    resources :wechat_tags do
      member do
        get :users
      end
    end

    root 'sessions#new'
  end

  namespace :wechat do
    get 'home', to: 'home#index'
    get 'user' => 'user#index'

    resources :addresses

    resources :shared_logs, only: [:create] do
      resource :user
    end
  end


  root  'visitors#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
  before_action :require_admin

  def require_admin
    if current_admin.blank?
      if wechat_agent?
        redirect_to wechat_home_path
      else
        redirect_to admin_root_path, alert: '请先登录'
      end
    end
  end

  helper_method :current_admin
  def current_admin
    return @current_admin if @current_admin.present?
    @current_admin = User.admin.find_by(id: session[:admin_id]) if session[:admin_id].present?
  end

  def current_admin=(user)
    return nil if user.blank?
    session[:admin_id] = session[:user_id] = user.id
    @current_admin = user
  end

  [:to_top, :to_bottom, :higher, :lower].each do |action|
    define_method "move_#{action}" do
      moveable action
    end
  end

  def moveable action
    resources = controller_name.classify.constantize.find(params[:id])
    resources.send("move_#{action}") if resources
    redirect_back(fallback_location: admin_root_path)

  end

  def update_positions
    ActiveRecord::Base.transaction do
      params[:position].each do |id, index|
        controller_name.classify.constantize.find(id).set_list_position(index)
      end
    end
  end

end

app/controllers/wechat/base_controller.rb
class Wechat::BaseController < ApplicationController
  wechat_api
  layout 'wechat'
  # before_action :require_login
  before_action :save_view_log

  def save_view_log
    return if params[:shared_user_id].blank? || !logged_in?
    shared_user_id = params[:shared_user_id]
    return if current_user.id = shared_user_id.to_i
    uri = request.fullpath.split('?').first
    ViewLog.create(
        shared_user_id: shared_user_id,
        viewer_id: current_user.id,
        uri: uri
    )
  end

end

app/helpers/wechat/base_helper.rb
module Wechat::BaseHelper

  def current_signature
    @signature ||= Wechat.api.jsapi_ticket.signature(request.url)[:signature]
  end

  def use_default_share_uri?
    case controller_name
      when 'wechat_tags', 'welcome', 'users', 'wechat_users'
        return true
    end

    return false
  end

  def share_uri
    @shared_uri = wechat_home_url(shared_user_id: current_user.try(:id))
    return @share_uri if @share_uri.present?
    if use_default_share_uri?
      wechat_home_url(shared_user_id: current_user.try(:id))
    else
      url_for(params.merge(shared_user_id: current_user.try(:id), only_path: false).permit!)
    end
  end

  def hide_share
    # return true if controller_name == 'consultants' && action_name == 'qrcode'
    # return true if controller_name == 'games'
    # return true if controller_name == 'home' && action_name == 'protocol'
    # return false
  end
end

app/views/admin/base/_flash.html.slim
.row.flash-wrapper
  - if flash[:notice]
    .alert.alert-info.alert-dismissable
      button.close type='button' aria-hidden='true' data-dismiss='alert' x
      = flash[:notice]
  - if flash[:alert]
    .alert.alert-warning.alert-dismissable
      button.close type='button' aria-hidden='true' data-dismiss='alert' x
      = flash[:alert]
      

app/views/admin/base/_move.html.slim
= link_to [:move_to_top, :admin, resource], class: 'btn btn-white btn-sm', method: :post do
  i.fa.fa-angle-double-up
  | &nbsp;TOP
= link_to [:move_higher, :admin, resource], class: 'btn btn-white btn-sm', method: :post do
  i.fa.fa-angle-up
  | &nbsp;Up
= link_to [:move_lower, :admin, resource], class: 'btn btn-white btn-sm', method: :post do
  i.fa.fa-angle-down
  | &nbsp;Down
= link_to [:move_to_bottom, :admin, resource], class: 'btn btn-white btn-sm', method: :post do
  i.fa.fa-angle-double-down
  | &nbsp;Bottom

app/views/admin/base/_navbar.html.slim
nav.navbar-default.navbar-static-side role='navigation'
  .sidebar-collapse
    #side-menu.nav.metismenu
      li.nav-header
        .dropdown.profile-element
          - if logged_in_as_admin?
            .span
              /= image_tag current_admin.headimageurl, class: 'img-circle', size: '50x50'
            = link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
              span.clear
                span.block.m-t-xs
                  strong.font-bold= link_to current_admin.nickname, admin_user_path(current_admin)
                  span.text-muted.text-xs.block 管理员
                .logo-element= "wechat"
              li
                = link_to '#' do
                  i.fa.fa-users
                  span.nav-label= "用户"
                  span.fa.arrow
                ul.nav.nav-second-level.collapse
                  li
                    = link_to "用户", admin_users_path
                ul.nav.nav-second-level.collapse
                  li
                    = link_to "地址"
              li
                = link_to '#' do
                  i.fa.fa-th-large
                  span.nav-label 关注用户
                  span.fa.arrow
                ul.nav.nav-second-level.collapse
                  li
                    = link_to '关注用户', admin_wechat_users_path
              li
                = link_to '#' do
                  i.fa.fa-wechat
                  span.nav-label 微信
                  span.fa.arrow
                ul.nav.nav-second-level.collapse
                  li
                    = link_to '标签', admin_wechat_tags_path
              li
                = link_to '#' do
                  i.fa.fa-wrench
                  span.nav-label 设置
                  span.fa.arrow
                ul.nav.nav-second-level.collapse
                  li
                    = link_to 'Faq', admin_faqs_path

              li
                = link_to '#' do
                  i.fa.fa-database
                  span.nav-label 日志
                  span.fa.arrow
                ul.nav.nav-second-level.collapse
                  li
                    = link_to '分享', admin_shared_logs_path
                  li
                    = link_to '分享点击', admin_view_logs_path

app/views/admin/base/_navbar_header.html.slim
.row.border-bottom
  nav.navbar.navbar-static-top.white-bg role='navigation' style='margin-bottom: 0'
    .navbar-header
      a class='navbar-minimalize minimalize-styl-2 btn btn-primary' href='#'
        i class='fa fa-bars'
    ul.nav.navbar-top-links.navbar-right
      li
        span.m-r-sm.text-muted.welcome-message= "微信测试号后台"

      /li
      /  = link_to logout_path, method: "delete" do
      /    i.fa.fa-sign-out= "登录"
      li
        /= link_to signup_path do
          i.fa.fa-sign-in=  "注册"
        /= link_to "Log out", logout_path, method: "delete"
        - if logged_in?
          /li= link_to "Users", users_path
          /li= link_to " WechatUser", wechat_users_path
          /li= link_to "About", users_path, id: "logo"
          /li= link_to "SharedLog", shared_logs_path
          li.dropdown
            a.dropdown-toggle data-toggle="dropdown" href="#"
              | 账户
              b.caret
            ul.dropdown-menu
              /li= link_to "个人信息", admin_user_path(current_admin)
              li= link_to "设置", edit_admin_user_path(current_user)
              li.divider

              li
                = link_to admin_logout_path, method: "delete" do
                  i.fa.fa-sign-out= "退出登录"
        /- else
        /
        /    li= link_to admin_login_path do
        /      i.fa.fa-sign-out= "登录"

            /li= link_to "UserInfo", current_user

app/views/admin/base/_subnav.html.slim
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-8
    /h2= t("admin.#{controller_name}")
    ol.breadcrumb
      li= link_to '首页', admin_users_path
      - if action_name == 'index'
        li.active= "列表"
      - else
        li= link_to "列表", controller: controller_name, action: :index
        /li.active
        /  - if %w(new create edit update show).include?(action_name)
        /    = t("#{action_name}")
        /  - else
        /    = t("admin.#{controller_name}.#{action_name}")
  /.col-lg-4
  /  .title-action
  /    - if action_name == 'index'
  /      - if have_new_btn?
  /        = link_to '添加', {controller: controller_name, action: :new}, class: 'btn btn-sm btn-primary'
  /    - else
  /      = link_to '返回', {controller: controller_name, action: :index}, class: 'btn btn-sm btn-primary'