config/routes.rb
Rails.application.routes.draw do
  resource :wechat, only: [:show, :create]
  resources :visitors
  get 'auth/wechat/callback', to: 'wechat/welcome#create'

  mount ChinaCity::Engine => '/china_city'

  namespace :admin do
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    resources :users
    resources :faqs do
      member do
        post :move_to_top
        post :move_to_bottom
        post :move_higher
        post :move_lower
      end
    end
    resources :wechat_users
    resources :view_logs
    resources :addresses
    resources :shared_logs, only: [:index, :create]
    resources :wechat_tags
    resources :users, only: [:index, :show, :update] do
      resources :shared_logs, only:[:index]
      resources :wiew_logs, only: [:index]
    end

    resources :wechat_tags do
      member do
        get :users
      end
    end

    root 'sessions#new'
  end

  namespace :wechat do
    get 'home', to: 'home#index'
    get 'user' => 'user#index'

    resources :addresses

    resources :shared_logs, only: [:create] do
      resource :user
    end
  end


  root  'visitors#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wechat_tag.rb
class WechatTag < ApplicationRecord

  enum tag_type: [:as_normal, :as_role, :as_group]

  validates :name, presence:true, uniqueness:true
  # has_many :users, through: :user_wechat_tags

  has_and_belongs_to_many :users

  before_create :add_to_wechat, if: 'tagid.blank?'
  after_create  :update_to_wechat, if: 'name_changed?'
  after_destroy :delete_to_wechat

  def add_to_wechat
    begin
      res = Wechat.api.tag_create(self.name)
      self[:tagid] = res['tag']['id']
      raise res if res['errmsg'] != 'ok'
    rescue => e
      _tags = Wechat.api.tags['tags']
      t = _tags.select{|t| t['name'] == self.name}
      if t.present?
        self[:tagid] = t[0]['id']
      else
        errors.add(:base, '不能添加微信标签')
        throw(:abort)
      end
    end
  end

  def update_to_wechat
    begin
      res = Wechat.api.tag_update(self.tagid, self.name)
      raise res if res['errmsg'] != 'ok'
    rescue
      errors.add(:base, '不能更新微信标签')
      # throw(:abort)
    end
  end

  def delete_to_wechat
    begin
      res = Wechat.api.tag_delete(self.tagid)
      raise res if res['errmsg'] != 'ok'
    rescue
      errors.add(:base, '未能删除微信标签')
      throw(:abort)
    end
  end

  def self.sync_from_wechat
    _tags = Wechat.api.tags['tags']
    _tags.each do |t|
      tag = WechatTag.find_or_initialize_by(name: t['name'])
      tag.tagid = t['id']
      tag.save(validate: false)
    end
  end

  def self.select_options
    self.all.pluck(:name, :id)
  end

  def self.tag_type_options
    self.tag_types.map{|k,v| [WechatTag.human_attribute_name("tag_type.#{k}"),k]}
  end
end

app/controllers/admin/wechat_tags_controller.rb
class Admin::WechatTagsController < Admin::BaseController

    before_action :fetch_tag, only: [:show, :edit, :update, :destroy, :users]

    def index
      @wechat_tags = WechatTag.all.includes(:users).page(params[:page]||1).per(20)
    end

    def show


    end

    def edit

    end

    def new
      @wechat_tag = WechatTag.new
    end

    def create
      @wechat_tag = WechatTag.create(wechat_tag_params)
      if @wechat_tag.save
        flash[:notice] = "保存成功"
        redirect_to admin_wechat_tags_path
      else
        render action: 'new'
      end
    end

    def update
      @wechat_tag = WechatTag.find(params[:id])
      @wechat_tag.update(wechat_tag_params)
      if @wechat_tag.save
        flash[:notice] = "更新成功"
        redirect_to admin_wechat_tags_path
      else
        redirect_to 'edit'
      end
    end

    def destroy
      @wechat_tag = WechatTag.find(params[:id])
      @wechat_tag.destroy
      flash[:notice] = "删除成功"
      redirect_to admin_wechat_tags_path
    end

    def users
      @users = @wechat_tag.users
      render :edit
    end

    private
    def fetch_tag
      @wechat_tag = WechatTag.find(params[:id])
    end

    def wechat_tag_params
      params.require(:wechat_tag).permit(:name, :tag_type)
    end

end

app/controllers/wechat_tag_controller.rb
class WechatTagController < ApplicationController

  before_action :fetch_tag, only: [:show, :edit, :update, :destroy, :users]

  def index
    @wechat_tags = WechatTag.all
  end

  def show

  end

  def edit

  end

  def new
    @wechat_tag = WechatTag.new
  end

  def create
    @wechat_tag = WechatTag.create(wechat_tag_params)
    if @wechat_tag.save
      flash[:notice] = "保存成功"
      redirect_to wechat_tag_path
    else
      render action: 'new'
    end
  end

  def update
    @wechat_tag = WechatTag.find(params[:id])
    @wechat_tag.update(wechat_tag_params)
    if @wechat_tag.save
      flash[:notice] = "更新成功"
    else
      redirect_to 'edit'
    end
  end

  def destroy
    @wechat_tag = WechatTag.find(params[:id])
    @wechat_tag.destroy
    flash[:notice] = "删除成功"
    redirect_to wechat_tag_path
  end

  def users
    @users = @wechat_tag.users
    render :edit
  end

  private
  def fetch_tag
    @wechat_tag = WechatTag.find(params[:id])
  end

  def wechat_tag_params
    params.require(:wechat_tag).permit(:name, :tag_type)
  end

end

app/helpers/admin/wechat_tags_helper.rb
module Admin::WechatTagsHelper
end

app/helpers/wechat_tags_helper.rb
module WechatTagsHelper
  def enum_color(_id)
    return '' if _id.blank?
    colors = %W(plain primary info success warning danger)
    colors[_id%6]
  end

  def have_new_btn?
    return false if %w(users wechat_tags).include?(controller_name)
    return true
  end
end

app/views/admin/wechat_tags/_form.html.slim
= simple_form_for([:admin, @wechat_tag], html: {class: 'form-horizontal wechat_tag'}, wrapper: :horizontal_form) do |f|
  = f.input :name
  = f.input :tag_type, as: :select, collection: WechatTag.tag_type_options
  .form-group
    .col-md-offset-3.col-md-9
      = f.submit '保存', class: 'btn btn-primary'
  = link_to '返回', {controller: controller_name, action: :index}, class: 'btn btn-sm btn-primary'

app/views/admin/wechat_tags/edit.html.slim
= render 'admin/base/subnav'

.wrapper.wrapper-content.animated.fadeInRight
  .tabs-container
    ul.nav.nav-tabs
      li class="#{'active' if %w(edit update).include?(action_name) }"
        = link_to t('edit'), edit_admin_wechat_tag_path(@wechat_tag)
      li class="#{'active' if action_name == 'users' }"
        = link_to '用户', admin_wechat_tags_path(@wechat_tag)
    .tab-content
      #tab-detail.tab-pane.active
        .panel-body
          - if controller_name == 'wechat_tags' && %w(edit update).include?(action_name)
            = render 'form'
          - elsif action_name == 'users'
            = render 'admin/users/list'

app/views/admin/wechat_tags/index.html.slim
h1.row.col-md-4.col-md-offset-5  Wechat_tags
= render 'admin/base/subnav'
/= current_user.inspect
col-lg-4.white-bg
  .title-action
    /- if action_name == 'index'
    /  - if have_new_btn?
    /- else
.wrapper.wrapper-content.animated.fadeInRight
  .ibox.float-e-margins
    .ibox-content
      small="Total: #{WechatTag.count}"
      /small="Total: #{@wechat_tags.total_count}"

      table.table.table-striped
        tr
          th ID
          th= WechatTag.human_attribute_name(:name)
          /th= WechatTag.human_attribute_name(:tag_type)
          th= WechatTag.human_attribute_name(:tagid)
          th= WechatTag.human_attribute_name(:tag_type)
          th 用户数
          th= link_to '添加', {controller: controller_name, action: :new}, class: 'btn btn-sm btn-primary'

        - @wechat_tags.each do |resource|
          tr
            td= resource.id
            td= resource.name
            td= resource.tagid
            td
              .label class="label-#{enum_color(WechatTag.tag_types.fetch(resource.tag_type))}"
                = WechatTag.human_attribute_name("tag_type.#{resource.tag_type}")
            /td= resource.tag_type
            td
              = link_to resource.users.size, users_admin_wechat_tag_path(resource)
            td
              .btn-group
                = link_to '编辑', edit_admin_wechat_tag_path(resource), class: 'btn btn-white btn-sm'
                = link_to '删除', [:admin, resource], :method => :delete, :data => { :confirm => 'are you sure?' },
                        class: 'btn btn-white btn-sm'

      .pageList.text-center
        = paginate @wechat_tags